version: "3.9"

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: arte
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config
      # - TS_SERVE_CONFIG=/config/serve.json
      
    volumes:
      - tailscale-data:/var/lib/tailscale
      - ./tailscale/serve.json:/config/serve.json
    networks:
      - internal
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: resourcespace
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /opt/stacks/resourcespace/db:/var/lib/mysql
    restart: unless-stopped
    ### does this config need a network definition?
    # networks:
    # - internal

  resourcespace:
    build: .
    container_name: resourcespace
    depends_on:
      - mariadb
    environment:
      RS_DB_HOST: mariadb
      RS_DB_NAME: resourcespace
      RS_DB_USER: ${MYSQL_USER}
      RS_DB_PASS: ${MYSQL_PASSWORD}
    volumes:
      - /opt/stacks/resourcespace/filestore:/var/www/html/filestore
      - /opt/stacks/resourcespace/config:/var/www/html/include
    networks:
      - internal
    restart: unless-stopped

  rs-cron:
    build: .
    container_name: rs-cron
    depends_on:
      - mariadb
    command: ["/bin/bash", "/cron.sh"]
    volumes:
      - /opt/stacks/resourcespace/filestore:/var/www/html/filestore
      - /opt/stacks/resourcespace/config:/var/www/html/include
      - ./cron.sh:/cron.sh
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  tailscale-data:
