version: "3.9"

services:
  tailscale:
    image: tailscale/tailscale:latest
    ##### Recommended removal of container_name to avoid conflicts if redeploying
    # container_name: tailscale-rs
    #####
    hostname: ${TS_HOSTNAME:-resourcespace}
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "true"
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
    volumes:
      - tailscale-data:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    command: >
      sh -c "
        tailscaled &
        sleep 3 &&
        tailscale up --authkey=${TS_AUTHKEY} --hostname=${TS_HOSTNAME:-resourcespace} ${TS_EXTRA_ARGS} --reset &&
        tailscale funnel ${TS_FUNNEL_PORT:-80}
      "

  resourcespace:
    user: "33:33"
    build: .
    ##### Recommended removal of container_name to avoid conflicts if redeploying
    # container_name: resourcespace
    #####
    restart: unless-stopped
    depends_on:
      - mariadb
      - tailscale
    network_mode: service:tailscale
    volumes:
      - /opt/stacks/resourcespace/filestore:/var/www/html/filestore
      
      # Enable config.php mount below
      # only after running installer on first deployment
      # so ResourceSpace can generate the config
      # that we copy out of the container into the file bound in the line below
      # - /opt/stacks/resourcespace/config/config.php:/var/www/html/include/config.php
      ###################################################
      
    environment:
      RS_DB_HOST: ${RS_DB_HOST:-mariadb}
      RS_DB_NAME: ${MYSQL_DATABASE}
      RS_DB_USER: ${MYSQL_USER}
      RS_DB_PASS: ${MYSQL_PASSWORD}

  mariadb:
    user: "999:999"
    image: mariadb:${MARIADB_VERSION:-11}
    ##### Recommended removal of container_name to avoid conflicts if redeploying
    # container_name: mariadb
    #####
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-resourcespace}
      MYSQL_USER: ${MYSQL_USER:-rsuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /opt/stacks/resourcespace/db:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb:
  filestore:
  tailscale-data:
